version: "3"
services:
  node:
    image: node:latest
    container_name: openshift-node
    restart: unless-stopped
    tty: true
    working_dir: /home/app
    environment: 
         OWM_API_KEY: ad969323b74ab91c6f35e3d3428e18f9
    ports:
      - "9090:8000"
    volumes:
      - "./app:/home/app"
    entrypoint: 
        - node
        - index.js
